config/routes.rb
Rails.application.routes.draw do
  root to: 'homes#top'
  get 'homes/about' => 'homes#about'

  devise_for :admins, controllers: {
    sessions: 'admins/sessions'
  }
  devise_for :customers
  namespace :public do
    resources :customers, only: [:show, :edit, :update] do
      member do
        get "confirm"
        #ユーザーの会員状況を取得
        patch "hide"
        #ユーザーの会員状況を更新
      end
    end

    resources :cart_items, only: [:index, :update, :destroy] do
      collection do
        delete 'empty'
      end
    end

    resources :items, only: [:index, :show, :create] do
      resources :cart_items, only: [:create]
    end
    get 'orders/confirm' => 'orders#confirm'
    get 'orders/complete' => 'orders#complete'
    resources :orders, only: [:new, :create, :index, :show]

    resources :addresses, only: [:index, :create, :destroy, :edit, :update]

  end

  namespace :admin do
    root to: 'homes#top'
    resources :items
    resources :genres, only: [:index, :create, :edit, :update]
    resources :customers, only: [:index, :show, :edit, :update]
    resources :orders, only: [:index, :show, :update] do
      resources :order_items, only: [:update]
    end
  end

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/customer.rb
class Customer < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  validates :first_name, :last_name, :kana_first_name, :kana_last_name, :postal_code,
            :address, :telephone_number, presence: true
  validates :is_deleted, inclusion:{in: [true, false]}
  has_many :orders
  has_many :cart_items
  has_many :addresses
  def active_for_authentication?
    super && (self.is_deleted == false)
  end

end

app/controllers/admin/customers_controller.rb
class Admin::CustomersController < ApplicationController
  def index
    @customers = Customer.all.page(params[:page]).per(5)
  end

  def show
    @customer = Customer.find(params[:id])
  end

  def edit
    @customer = Customer.find(params[:id])
  end

  def update
    @customer = Customer.find(params[:id])
    if @customer.update(customer_params)
      flash[:success] = "会員情報を変更しました"
      redirect_to admin_customer_path(@customer)
    else
      render :edit
    end
  end

  private
	def customer_params
	  params.require(:customer).permit(:first_name,:last_name,:kana_first_name,:kana_last_name,:postal_code,:address,:telephone_number,:email,:is_deleted)
	end
end

app/controllers/customers/confirmations_controller.rb
# frozen_string_literal: true

class Customers::ConfirmationsController < Devise::ConfirmationsController
  # GET /resource/confirmation/new
  # def new
  #   super
  # end

  # POST /resource/confirmation
  # def create
  #   super
  # end

  # GET /resource/confirmation?confirmation_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after resending confirmation instructions.
  # def after_resending_confirmation_instructions_path_for(resource_name)
  #   super(resource_name)
  # end

  # The path used after confirmation.
  # def after_confirmation_path_for(resource_name, resource)
  #   super(resource_name, resource)
  # end
end

app/controllers/customers/omniauth_callbacks_controller.rb
# frozen_string_literal: true

class Customers::OmniauthCallbacksController < Devise::OmniauthCallbacksController
  # You should configure your model like this:
  # devise :omniauthable, omniauth_providers: [:twitter]

  # You should also create an action method in this controller like this:
  # def twitter
  # end

  # More info at:
  # https://github.com/heartcombo/devise#omniauth

  # GET|POST /resource/auth/twitter
  # def passthru
  #   super
  # end

  # GET|POST /users/auth/twitter/callback
  # def failure
  #   super
  # end

  # protected

  # The path used when OmniAuth fails
  # def after_omniauth_failure_path_for(scope)
  #   super(scope)
  # end
end

app/controllers/customers/passwords_controller.rb
# frozen_string_literal: true

class Customers::PasswordsController < Devise::PasswordsController
  # GET /resource/password/new
  # def new
  #   super
  # end

  # POST /resource/password
  # def create
  #   super
  # end

  # GET /resource/password/edit?reset_password_token=abcdef
  # def edit
  #   super
  # end

  # PUT /resource/password
  # def update
  #   super
  # end

  # protected

  # def after_resetting_password_path_for(resource)
  #   super(resource)
  # end

  # The path used after sending reset password instructions
  # def after_sending_reset_password_instructions_path_for(resource_name)
  #   super(resource_name)
  # end
end

app/controllers/customers/registrations_controller.rb
# frozen_string_literal: true

class Customers::RegistrationsController < Devise::RegistrationsController
  # before_action :configure_sign_up_params, only: [:create]
  # before_action :configure_account_update_params, only: [:update]

  # GET /resource/sign_up
  # def new
  #   super
  # end

  # POST /resource
  # def create
  #   super
  # end

  # GET /resource/edit
  # def edit
  #   super
  # end

  # PUT /resource
  # def update
  #   super
  # end

  # DELETE /resource
  # def destroy
  #   super
  # end

  # GET /resource/cancel
  # Forces the session data which is usually expired after sign
  # in to be expired now. This is useful if the user wants to
  # cancel oauth signing in/up in the middle of the process,
  # removing all OAuth session data.
  # def cancel
  #   super
  # end

  # protected

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_sign_up_params
  #   devise_parameter_sanitizer.permit(:sign_up, keys: [:attribute])
  # end

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_account_update_params
  #   devise_parameter_sanitizer.permit(:account_update, keys: [:attribute])
  # end

  # The path used after sign up.
  # def after_sign_up_path_for(resource)
  #   super(resource)
  # end

  # The path used after sign up for inactive accounts.
  # def after_inactive_sign_up_path_for(resource)
  #   super(resource)
  # end
end

app/controllers/customers/sessions_controller.rb
# frozen_string_literal: true

class Customers::SessionsController < Devise::SessionsController
  # before_action :configure_sign_in_params, only: [:create]
   before_action :reject_customer, only: [:create]

  # GET /resource/sign_in
  # def new
  #   super
  # end

  # POST /resource/sign_in
  # def create
  #   super
  # end

  # DELETE /resource/sign_out
  # def destroy
  #   super
  # end

  protected

  def reject_customer
    @customer = Customer.find_by(email: params[:customer][:email].downcase)
    if @customer
      if (@customer.valid_password?(params[:customer][:password]) && (@customer.active_for_authentication? == false))
        flash[:notice] = "このアカウントは退会済みです"
        redirect_to new_customer_session_path
      end
    else
      flash[:notice] = "必須項目を入力してください。"
    end
  end


  # If you have extra params to permit, append them to the sanitizer.
  # def configure_sign_in_params
  #   devise_parameter_sanitizer.permit(:sign_in, keys: [:attribute])
  # end
end

app/controllers/customers/unlocks_controller.rb
# frozen_string_literal: true

class Customers::UnlocksController < Devise::UnlocksController
  # GET /resource/unlock/new
  # def new
  #   super
  # end

  # POST /resource/unlock
  # def create
  #   super
  # end

  # GET /resource/unlock?unlock_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after sending unlock password instructions
  # def after_sending_unlock_instructions_path_for(resource)
  #   super(resource)
  # end

  # The path used after unlocking the resource
  # def after_unlock_path_for(resource)
  #   super(resource)
  # end
end

app/helpers/admin/customers_helper.rb
module Admin::CustomersHelper
end

app/views/admin/customers/edit.html.erb
<div class = "container">
<h2><%= @customer.first_name %><%= @customer.last_name %>さんの会員情報編集</h2>
  <div class = "row">
    <div class="my-5">
      <%= form_with model:@customer, url:admin_customer_path(@customer),local:true do |f| %>
        <table class="table table-borderless">
          <tr class="d-flex">
            <th class="col-3"><%= f.label :"会員ID" %></th>
            <td class="col-9"><%= f.label :"#{@customer.id}" %></td>
          </tr>
          <tr class="d-flex">
            <th class="col-3"><%= f.label :"氏名" %></th>
            <td class="col-9"><%= f.text_field :first_name %><%= f.text_field :last_name %></td>
          </tr>
          <tr class="d-flex">
            <th class="col-3"><%= f.label :"フリガナ" %></th>
            <td class="col-9"><%= f.text_field :kana_first_name %><%= f.text_field :kana_last_name %></td>
          </tr>
          <tr class="d-flex">
            <th class="col-3"><%= f.label :"郵便番号" %></th>
            <td class="col-9"><%= f.text_field :postal_code %></td>
          </tr>
          <tr class="d-flex">
            <th class="col-3"><%= f.label :"住所" %></th>
            <td class="col-9"><%= f.text_field :address, size: 80 %></td>
          </tr>
          <tr class="d-flex">
            <th class="col-3"><%= f.label :"電話番号" %></th>
            <td class="col-9"><%= f.text_field :telephone_number %></td>
          </tr>
          <tr class="d-flex">
            <th class="col-3"><%= f.label :"メールアドレス" %></th>
            <td class="col-9"><%= f.text_field :email %></td>
          </tr>
          <tr class="d-flex">
            <th class="col-3"><%= f.label :"会員ステータス" %></th>
            <td class="col-9">
              <%= f.radio_button :is_deleted, false %>
              <%= f.label :is_deleted, "有効" %>
              <%= f.radio_button :is_deleted, true %>
              <%= f.label :is_deleted, "退会" %>
            </td>
          </tr>
        </table>
        <div>
          <%= f.submit "変更を保存する", class: "btn btn-success"%>
        </div>
      <% end %>
    </div>
  </div>
</div>

app/views/admin/customers/index.html.erb
<div class="container">
  <h2>会員一覧</h2>
  <div class="row">
    <div class="col-12">
      <table class="table">
        <thead class="table-active">
          <tr>
            <th>会員ID</th>
            <th>氏名</th>
            <th>メールアドレス</th>
            <th>ステータス</th>
          </tr>
        </thead>
        <tbody>
          <% @customers.each do |customer| %>
            <tr>
              <td>
                <%= customer.id %>
              </td>
              <td>
                <%= link_to admin_customer_path(customer), :style=>"color:black;" do %>
                  <%= customer.first_name %><%= customer.last_name %>
                <% end %>
              </td>
              <td>
                <%= customer.email %>
              </td>
              <td>
                <% if customer.is_deleted == true %>
                  <p class = "text-secondary">退会</p>
                <% else %>
                  <p class = "text-success">有効</p>
                <% end %>
              </td>
            </tr>
          <% end %>
        </tbody>
      </table>
    </div>
  </div>
</div>
<div class="mx-auto" style="width: 200px"><%= paginate @customers %></div>

app/views/admin/customers/show.html.erb
<div class="container">
<h2><%= @customer.first_name %><%= @customer.last_name %>さんの会員詳細</h2>
<%= flash[:success] %>
 <div class="row">
  <div>
    <table class="table table-borderless">
      <tr class="d-flex">
        <th class="col-6">顧客ID</th>
        <td class="col-6"><%= @customer.id %></td>
      </tr>
      <tr class="d-flex">
        <th class="col-6">氏名</th>
        <td class="col-6"><%= @customer.first_name %><%= @customer.last_name %></td>
      </tr>
      <tr class="d-flex">
        <th class="col-6">フリガナ</th>
        <td class="col-9"><%= @customer.kana_first_name %><%= @customer.kana_last_name %></td>
      </tr>
      <tr class="d-flex">
        <th class="col-6">郵便番号</th>
        <td class="col-3"><%= @customer.postal_code %></td>
      </tr>
      <tr class="d-flex">
        <th class="col-6">住所</th>
        <td class="col-12"><%= @customer.address %></td>
      </tr>
      <tr class="d-flex"> 
        <th class="col-6">電話番号</th>
        <td class="col-12"><%= @customer.telephone_number %></td>
      </tr>
      <tr class="d-flex">
        <th class="col-6">メールアドレス</th>
        <td class="col-3"><%= @customer.email %></td>
      </tr>
      <tr class="d-flex">
        <th class="col-6">会員ステータス</th>
        <td class="col-3">
          <% if @customer.is_deleted == true %>
            <p class = "text-secondary">無効</p>
          <% elsif @customer.is_deleted == false %>
            <p class = "text-success">有効</p>
          <% end %>
        </td>
      </tr>
    </table>
    </div>
  </div>
</div>
<div class="row justify-content-center">
  <div style="padding: 20px;">
  <%= link_to "編集する",edit_admin_customer_path(@customer), class: "btn btn-success" %>
  </div>
  <div style="padding: 20px;">
  <%= link_to " 注文履歴一覧を見る", admin_orders_path, class: "btn btn-primary" %>
  </div>
</div>