config/routes.rb
Rails.application.routes.draw do
  root to: 'homes#top'
  get 'homes/about' => 'homes#about'

  devise_for :admins, controllers: {
    sessions: 'admins/sessions'
  }
  devise_for :customers
  namespace :public do
    resources :customers, only: [:show, :edit, :update] do
      member do
        get "confirm"
        #ユーザーの会員状況を取得
        patch "hide"
        #ユーザーの会員状況を更新
      end
    end

    resources :cart_items, only: [:index, :update, :destroy] do
      collection do
        delete 'empty'
      end
    end

    resources :items, only: [:index, :show, :create] do
      resources :cart_items, only: [:create]
    end
    get 'orders/confirm' => 'orders#confirm'
    get 'orders/complete' => 'orders#complete'
    resources :orders, only: [:new, :create, :index, :show]

    resources :addresses, only: [:index, :create, :destroy, :edit, :update]

  end

  namespace :admin do
    root to: 'homes#top'
    resources :items
    resources :genres, only: [:index, :create, :edit, :update]
    resources :customers, only: [:index, :show, :edit, :update]
    resources :orders, only: [:index, :show, :update] do
      resources :order_items, only: [:update]
    end
  end

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/address.rb
  class Address < ApplicationRecord
    belongs_to :customer
    validates :customer_id, :postal_code, :address, :name, presence: true

    def resistration
  		"〒" + self.postal_code + "　" + self.address + "　" + self.name
  	end
  end

app/models/admin.rb
class Admin < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/cart_item.rb
class CartItem < ApplicationRecord
  belongs_to :customer
  belongs_to :item
  validates :customer_id, :item_id, :count, presence: true
  

end

app/models/customer.rb
class Customer < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  validates :first_name, :last_name, :kana_first_name, :kana_last_name, :postal_code,
            :address, :telephone_number, presence: true
  validates :is_deleted, inclusion:{in: [true, false]}
  has_many :orders
  has_many :cart_items
  has_many :addresses
  def active_for_authentication?
    super && (self.is_deleted == false)
  end

end

app/models/genre.rb
class Genre < ApplicationRecord
  has_many :items
  validates :name, presence: true, uniqueness: true
end

app/models/item.rb
class Item < ApplicationRecord

  has_many :order_items
  has_many :cart_items
  belongs_to :genre
  attachment :image
  validates :name, uniqueness: true
  # validates :genre_id, :name, :detail, :image_id, :price, :is_sold, presence: true

end

app/models/order.rb
class Order < ApplicationRecord
    belongs_to :customer
    has_many :order_items
    attachment :image
    enum status: { "入金待ち": 0, "入金確認": 1, "製作中": 2, "発送準備中": 3, "発送済み": 4 }
    validates :customer_id, :payment_method, :status, :address, :postal_code,
              :name, :shipping_cost, :total_price, presence: true
    enum address_option: { "ご自身の住所": 0, "登録済住所から選択": 1, "新しいお届け先": 2 }
    enum payment_method: { "クレジットカード": 0, "銀行振り込み": 1}

end

app/models/order_item.rb
class OrderItem < ApplicationRecord
  belongs_to :order
  belongs_to :item
  enum making_status: { "着手不可": 0, "製作待ち": 1, "製作中": 2, "製作完了": 3 }

  validates :item_id, :order_id, :count, :making_status, :purchased_price, presence: true
end

app/controllers/admin/genres_controller.rb
class Admin::GenresController < ApplicationController
  def index
    @genre = Genre.new
    @genres = Genre.all
  end

  def create
    @genre = Genre.new(genre_params)
    if @genre.save
      flash[:success] = "ジャンルを追加しました"
      redirect_to admin_genres_path
    else
      @genres = Genre.all
      render :index
    end
  end

  def edit
    @genre = Genre.find(params[:id])
  end

  def update
    @genre = Genre.find(params[:id])
    if @genre.update(genre_params)
      flash[:success] = "ジャンルを変更しました"
      redirect_to admin_genres_path(@genre)
    else
      render :edit
    end
  end

  private

  def genre_params
    params.require(:genre).permit(:name, :is_valid)
  end
end

app/controllers/admin/homes_controller.rb
class Admin::HomesController < ApplicationController
  def top
  end
end

app/controllers/admin/items_controller.rb
class Admin::ItemsController < ApplicationController
  def new
    @item = Item.new
  end

  def index
    @items = Item.all.page(params[:page]).per(4)
  end

  def create
    @item = Item.new(item_params)
    if @item.save
      flash[:success] = "新商品を登録しました"
      redirect_to admin_item_path(@item)
    else
      render :new
    end
  end

  def show
    @item = Item.find(params[:id])
  end

  def edit
    @item = Item.find(params[:id])
  end

  def update
    @item = Item.find(params[:id])
    if @item.update(item_params)
      flash[:success] = "商品内容をを変更しました"
      redirect_to admin_item_path(@item)
    else
      render :edit
    end
  end

  private
  def item_params
    params.require(:item).permit(:name, :detail, :genre_id, :is_sold, :price)
  end
end

app/controllers/admin/orders_controller.rb
class Admin::OrdersController < ApplicationController
  def index
    @orders = Order.all
  end

  def show
    @order = Order.find(params[:id])
    @order_items = @order.order_items
    # 商品合計の計算方法
    @item_total = 0
    @order.order_items.each do |order_item|
      @item_total += order_item.purchased_price * order_item.count
    end
  end

  def update
    @order = Order.find(params[:id])
    if @order.update(status_params)
      flash[:success] = "注文ステータスを変更しました"
      redirect_to admin_order_path(@order)
    else
      render :show
    end
  end

  private
  def status_params
    params.require(:order).permit(:status)
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
  before_action :configure_permitted_parameters, if: :devise_controller?

  def after_sign_in_path_for(resource)
    public_customer_path(resource)
  end

  def after_sign_out_path_for(resource)
    root_path
  end

  protected

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [:first_name, :last_name, :kana_first_name, :kana_last_name,
      :postal_code, :address, :telephone_number, :is_deleted])

  end
end

app/controllers/homes_controller.rb
class HomesController < ApplicationController
  def top
    @item = Item.limit(4).order("created_at DESC")
    @tax = 1.08
  end

  def about
  end
end

app/helpers/admin/customers_helper.rb
module Admin::CustomersHelper
end

app/helpers/admin/genres_helper.rb
module Admin::GenresHelper
end

app/helpers/admin/homes_helper.rb
module Admin::HomesHelper
end

app/helpers/admin/items_helper.rb
module Admin::ItemsHelper
end

app/helpers/admin/order_items_helper.rb
module Admin::OrderItemsHelper
end

app/helpers/admin/orders_helper.rb
module Admin::OrdersHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/homes_helper.rb
module HomesHelper
end

app/views/admin/genres/edit.html.erb
<div class="container">
 <div class="row">
   <div class="col-4">
    <h2>ジャンル編集</h2>
    <%= form_with model:@genre, url: admin_genre_path(@genre.id), local:true do |f| %>
      <div>
        <%= f.label :"ジャンル名" %>
        <%= f.text_field :name %>
      </div>
      <div>
        <%= f.submit "変更保存", class: "btn btn-success" %>
      </div>
    <% end %>
    </div>
  </div>
</div>

app/views/admin/genres/index.html.erb
<div class="container">
 <div class="row">
  <div class="col-4">
    <h2>ジャンル一覧・編集</h2>
    <%= flash[:success] %>
    <%= form_with model: @genre, url: admin_genres_path,local:true do |f| %>
      <div class="form-group">
        <%= f.label :"ジャンル名" %>
        <%= f.text_field :name %>
      </div>
      <div>
        <%= f.submit "新規登録", class: "btn btn-success" %>
      </div>
    <% end %>
    <table class = "table">
      <thead class="table-active">
        <tr>
          <th>ジャンル</th>
          <th></th>
        </tr>
      </thead>
      <tbody>
        <% @genres.each do |genre| %>
          <tr>
            <td>
              <%= genre.name %>
            </td>
            <td>
              <%= link_to "編集する", edit_admin_genre_path(genre), class: "btn btn-success" %>
            </td>
          </tr>
        <% end %>
      </tbody>
    </table>
    </div>
  </div>
</div>

app/views/admin/items/_item_form.html.erb
<tr class="d-flex">
  <th class="col-6"><%= f.label :"商品名" %></th>
  <td class="col-6"><%= f.text_field :name %></td>
</tr>
<tr class="d-flex">
  <th class="col-6"><%= f.label :"商品説明" %></th>
  <td class="col-6"><%= f.text_area :detail %></td>
</tr>
<tr class="d-flex">
  <th class="col-6"><%= f.label :"ジャンル" %></th>
  <td class="col-6"><%= f.collection_select(:genre_id, Genre.all, :id, :name , prompt: "-- 選択してください --") %></td>
</tr>
<tr class="d-flex">
  <th class="col-6"><%= f.label :"税抜価格" %></th>
  <td class="col-6"><%= f.text_field :price, size: 10 %>円</td>
</tr>
<tr class="d-flex">
  <th class="col-6"><%= f.label :"販売ステータス" %></th>
  <td class="col-6">
    <%= f.label :is_sold, "販売中" %>
    <%= f.radio_button :is_sold, true %>
    <%= f.label :is_sold, "販売停止中" %>
    <%= f.radio_button :is_sold, false %>
  </td>
</tr>

app/views/admin/items/edit.html.erb
<div class = "container">
  <h2>商品編集</h2>
  <div class = "row">
    <div class="my-5">
    <%= form_with model:@item, url: admin_item_path(@item.id),local:true do |f| %>
      <table class="table table-borderless">
      <tr class="d-flex">
        <th class="col-6"><%= f.label :"商品画像" %></th>
        <td class="col-6"><%= f.attachment_field :image, class: " image" %></td>
      </tr>
      <%= render "item_form", f: f %>
    </table>
    <div class="mx-auto" style="width: 200px;">
      <%= f.submit "変更内容保存", class: "btn btn-success" %>
    </div>
    <% end %>
    </div>
  </div>
</div>

app/views/admin/items/index.html.erb
<div class="container">
<h2>商品一覧</h2>
 <div class="row">
  <div class="col-12">
      <%= link_to new_admin_item_path, class: "btn btn-warning float-right" do %>
        <i class="fas fa-plus"></i>
        新規登録
      <% end %>
    </div>
    <table class="table">
      <thead class="table-active">
        <tr class="info">
          <th>商品ID</th>
          <th>商品名</th>
          <th>税抜価格</th>
          <th>ジャンル</th>
          <th>ステータス</th>
        </tr>
      </thead>
      <tbody>
        <% @items.each do |item| %>
          <tr>
            <td>
              <%= item.id %>
            </td>
            <td>
              <%= link_to admin_item_path(item), :style=>"color:black;" do %>
                <%= item.name %>
              <% end %>
            </td>
            <td>
              ¥<%= item.price.to_s(:delimited) %>
            </td>
            <td>
              <%= item.genre.name %>
            </td>
            <td>
              <% if item.is_sold == true %>
                <p class = "text-success">販売中</p>
              <% elsif item.is_sold == false %>
                <p class = "text-secondary">販売停止中</p>
              <% end %>
            </td>
          </tr>
        <% end %>
      </tbody>
    </table>
  </div>
  </div>
</div>
<div class="mx-auto" style="width: 200px;"><%= paginate @items %></div>

app/views/admin/items/new.html.erb
<div class = "container">
<h2>商品新規登録</h2>
  <div class = "row">
    <div class="my-5">
<%= form_with model:@item,url: admin_items_path,local:true do |f| %>
        <table class="table table-borderless">
      <tr class="d-flex">
        <th class="col-6"><%= f.label :"商品画像" %></th>
        <td class="col-6"><%= f.attachment_field :image, class: " image" %></td>
      </tr>
      <%= render "item_form", f: f %>
    </table>
    <%= f.submit "新規登録", class: "btn btn-success" %>
<% end %>
</div>
</div>
</div>

app/views/admin/items/show.html.erb
<div class="container">
<h2>商品詳細</h2>
<%= flash[:success] %>
  <div class="row">
    <div class="col-3">
      <%= attachment_image_tag(@item, :image, size: "200x200", fallback: "no_image.jpg") %>
    </div>
    <div class="col-9">
      <table class="table table-borderless">
        <tr class="d-flex">
          <th class="col-3">商品名</th>
          <td class="col-3"><%= @item.name %></td>
        </tr>
        <tr class="d-flex">
          <th class="col-3">商品説明</th>
          <td class="col-3"><%= @item.detail %></td>
        </tr>
        <tr class="d-flex">
          <th class="col-3">ジャンル</th>
          <td class="col-3"><%= @item.genre.name %></td>
        </tr>
        <tr class="d-flex">
          <th class="col-3">
            <p>税込価格</p>
            <p>(税抜価格)</p>
          </th>
          <td class="col-3">
            <p><%= (@item.price * 1.08).round %>円</p>
            <p><%= @item.price %>円</p>
          </td>
        </tr>
        <tr class="d-flex">
          <th class="col-3">販売ステータス</th>
          <td class="col-3">
            <% if @item.is_sold == true %>
              <p class = "text-success">販売中</p>
            <% elsif @item.is_sold == false %>
              <p class = "text-secondary">販売停止中</p>
            <% end %>
          </td>
        </tr>
      </table>
<div class="mx-auto" style="width: 200px;">
  <%= link_to "編集する", edit_admin_item_path(@item), class: "btn btn-success" %>
</div>

app/views/admin/orders/index.html.erb
<div class="container">
  <div class="row">
    <div class="col">
      <h2>注文履歴一覧</h2>
      <table class="table table-hover table-bordered">
        <thead class="table-active">
          <tr class="info">
            <th>購入日時</th>
            <th>購入者</th>
            <th>注文個数</th>
            <th>注文ステータス</th>
          </tr>
        </thead>
        <tbody>
          <% @orders.each do |order| %>
            <tr>
              <td>
                <%= link_to admin_order_path(order), :style=>"color:black;" do %>
                  <%= order.created_at.strftime("%Y/%m/%d")  %>
                <% end %>
              </td>
              <td><%= order.customer.first_name %><%= order.customer.last_name %></td>
              <td><%= order.order_items.count%></td>
              <td><%= order.status%></td>
            </tr>
          <% end %>
        </tbody>
      </table>
    </div>
  </div>
</div>

app/views/admin/orders/show.html.erb
<div class="container">
  <div class="row">
    <div class="col">
      <h2>注文履歴詳細</h2>

      <table class="table table-hover table-bordered">
        <tbody>
          <tr>
            <td>購入者</td>
            <td>
              <%= link_to admin_customer_path(@order.customer), :style=>"color:black;" do %>
                <%= @order.customer.first_name %>
                <%= @order.customer.last_name %>
              <% end %>
            </td>
          </tr>
          <tr>
            <td>注文日</td>
            <td><%= @order.created_at.strftime("%Y/%m/%d") %></td>
          </tr>
          <tr>
            <td>配送先</td>
            <td><%= @order.address %></td>
          </tr>
          <tr>
            <td>支払方法</td>
            <td><%= @order.payment_method %></td>
          </tr>
          <tr>
            <td>注文ステータス</td>
            <td>
              <%= form_with model: @order, url:admin_order_path(@order), local:true do |f| %>
                <%= f.select :status, [['入金待ち'], ['入金確認'], ['製作中'], ['発送準備中'], ['発送済み']], prompt: "入金待ち" %>
                <%= f.submit "更新", class: "btn btn-sm btn-success" %>
              <% end %>
            </td>
          </tr>
        </tbody>
      </table>
      <div class="row">
      <div class="col">

      <table class="table table-hover table-bordered">
        <thead>
          <tr>
            <th>商品名</th>
            <th>単価（税込）</th>
            <th>数量</th>
            <th>小計</th>
            <th>制作ステータス</th>
            <th></th>
          </tr>
        </thead>
        <tbody>
        <% @order.order_items.each do |order_item| %>
          <tr>
            <td><%= order_item.item.name%></td>
            <td><%= order_item.item.price%></td>
            <td><%= order_item.item.detail%></td>
            <% tax = 1.08 %>
            <% subtotal = (order_item.item.price * tax * order_item.count).to_i.to_s(:delimited, delimiter: ',') %>
            <td><%= subtotal %></td>
          <%= form_with model:[order_item.order,order_item], url: admin_order_order_item_path(order_item.id), local:true do |f| %>
            <td><%= f.select :making_status, [['着手不可'], ['製作待ち'], ['製作中'],['製作完了']]%></td>
            <td><%= f.submit "更新", class: "btn btn-sm btn-success" %></td>
          <% end %>
          </tr>
        <% end %>
        </tbody>
      </table>
      </div>

      <div class="col-3 pt-5">
      <table>
        <tbody>
          <tr>
            <td>商品合計</td>
            <td><%= @item_total.to_s(:delimited) %>円</td>
          </tr>
          <tr>
            <td>送料</td>
            <td><%= @order.shipping_cost %>円</td>
          </tr>
          <tr>
            <td>請求金額合計</td>
            <td><%= @order.total_price %>円</td>
          </tr>
        </tbody>
      </table>
      </div>
      </div>