config/routes.rb
Rails.application.routes.draw do
  root to: 'homes#top'
  get 'homes/about' => 'homes#about'

  devise_for :admins, controllers: {
    sessions: 'admins/sessions'
  }
  devise_for :customers
  namespace :public do
    resources :customers, only: [:show, :edit, :update] do
      member do
        get "confirm"
        #ユーザーの会員状況を取得
        patch "hide"
        #ユーザーの会員状況を更新
      end
    end

    resources :cart_items, only: [:index, :update, :destroy] do
      collection do
        delete 'empty'
      end
    end

    resources :items, only: [:index, :show, :create] do
      resources :cart_items, only: [:create]
    end
    get 'orders/confirm' => 'orders#confirm'
    get 'orders/complete' => 'orders#complete'
    resources :orders, only: [:new, :create, :index, :show]

    resources :addresses, only: [:index, :create, :destroy, :edit, :update]

  end

  namespace :admin do
    root to: 'homes#top'
    resources :items
    resources :genres, only: [:index, :create, :edit, :update]
    resources :customers, only: [:index, :show, :edit, :update]
    resources :orders, only: [:index, :show, :update] do
      resources :order_items, only: [:update]
    end
  end

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/address.rb
  class Address < ApplicationRecord
    belongs_to :customer
    validates :customer_id, :postal_code, :address, :name, presence: true

    def resistration
  		"〒" + self.postal_code + "　" + self.address + "　" + self.name
  	end
  end

app/models/admin.rb
class Admin < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/cart_item.rb
class CartItem < ApplicationRecord
  belongs_to :customer
  belongs_to :item
  validates :customer_id, :item_id, :count, presence: true
  

end

app/models/customer.rb
class Customer < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  validates :first_name, :last_name, :kana_first_name, :kana_last_name, :postal_code,
            :address, :telephone_number, presence: true
  validates :is_deleted, inclusion:{in: [true, false]}
  has_many :orders
  has_many :cart_items
  has_many :addresses
  def active_for_authentication?
    super && (self.is_deleted == false)
  end

end

app/models/genre.rb
class Genre < ApplicationRecord
  has_many :items
  validates :name, presence: true, uniqueness: true
end

app/models/item.rb
class Item < ApplicationRecord

  has_many :order_items
  has_many :cart_items
  belongs_to :genre
  attachment :image
  validates :name, uniqueness: true
  # validates :genre_id, :name, :detail, :image_id, :price, :is_sold, presence: true

end

app/models/order.rb
class Order < ApplicationRecord
    belongs_to :customer
    has_many :order_items
    attachment :image
    enum status: { "入金待ち": 0, "入金確認": 1, "製作中": 2, "発送準備中": 3, "発送済み": 4 }
    validates :customer_id, :payment_method, :status, :address, :postal_code,
              :name, :shipping_cost, :total_price, presence: true
    enum address_option: { "ご自身の住所": 0, "登録済住所から選択": 1, "新しいお届け先": 2 }
    enum payment_method: { "クレジットカード": 0, "銀行振り込み": 1}

end

app/models/order_item.rb
class OrderItem < ApplicationRecord
  belongs_to :order
  belongs_to :item
  enum making_status: { "着手不可": 0, "製作待ち": 1, "製作中": 2, "製作完了": 3 }

  validates :item_id, :order_id, :count, :making_status, :purchased_price, presence: true
end

app/controllers/admin/homes_controller.rb
class Admin::HomesController < ApplicationController
  def top
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
  before_action :configure_permitted_parameters, if: :devise_controller?

  def after_sign_in_path_for(resource)
    public_customer_path(resource)
  end

  def after_sign_out_path_for(resource)
    root_path
  end

  protected

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [:first_name, :last_name, :kana_first_name, :kana_last_name,
      :postal_code, :address, :telephone_number, :is_deleted])

  end
end

app/controllers/homes_controller.rb
class HomesController < ApplicationController
  def top
    @item = Item.limit(4).order("created_at DESC")
    @tax = 1.08
  end

  def about
  end
end

app/helpers/admin/customers_helper.rb
module Admin::CustomersHelper
end

app/helpers/admin/genres_helper.rb
module Admin::GenresHelper
end

app/helpers/admin/homes_helper.rb
module Admin::HomesHelper
end

app/helpers/admin/items_helper.rb
module Admin::ItemsHelper
end

app/helpers/admin/order_items_helper.rb
module Admin::OrderItemsHelper
end

app/helpers/admin/orders_helper.rb
module Admin::OrdersHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/homes_helper.rb
module HomesHelper
end

app/views/admins/shared/_error_messages.html.erb
<% if resource.errors.any? %>
  <div id="error_explanation">
    <h2>
      <%= I18n.t("errors.messages.not_saved",
                 count: resource.errors.count,
                 resource: resource.class.model_name.human.downcase)
       %>
    </h2>
    <ul>
      <% resource.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
    </ul>
  </div>
<% end %>

app/views/admins/shared/_links.html.erb
<%- if controller_name != 'sessions' %>
  <%= link_to "Log in", new_session_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.registerable? && controller_name != 'registrations' %>
  <%= link_to "Sign up", new_registration_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.recoverable? && controller_name != 'passwords' && controller_name != 'registrations' %>
  <%= link_to "Forgot your password?", new_password_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.confirmable? && controller_name != 'confirmations' %>
  <%= link_to "Didn't receive confirmation instructions?", new_confirmation_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.lockable? && resource_class.unlock_strategy_enabled?(:email) && controller_name != 'unlocks' %>
  <%= link_to "Didn't receive unlock instructions?", new_unlock_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.omniauthable? %>
  <%- resource_class.omniauth_providers.each do |provider| %>
    <%= link_to "Sign in with #{OmniAuth::Utils.camelize(provider)}", omniauth_authorize_path(resource_name, provider) %><br />
  <% end %>
<% end %>

app/views/layouts/_error.html.erb
<% if element.errors.any? %>
  <div class = "error error-danger">
    <h2>入力内容にエラーが<%= element.errors.count %>件あります。</h2>
    <ul>
      <% element.errors.full_messages.each do |message| %>
        <li>error <%= message %></li>
      <% end %>
    </ul>
  </div>
<% end %>

app/views/layouts/_notifications.html.erb
<div class="error">
  <% flash.each do |key, value| %>
    <%= content_tag(:div, value, class: "#{key}") %>
  <% end %>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>NaganoCake</title>
    <%= csrf_meta_tags %>
    <meta name="viewport" content="width=device-width, initial-scale=1, maximum-scale=1">
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <header>
      <nav class="navbar navbar-expand-lg navbar-light ">
        <div class="container">
          <a class="navbar-brand p-3" href="/">
            <h3 class="title-logo font-weight-bold">ながの<span class="title-logo-2 font-weight-bold">CAKE</span></h3>
          </a>
            <%= render 'layouts/notifications' %>
          <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNavDropdown" aria-controls="navbarNavDropdown" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icgit on"></span>
          </button>
          <div class="collapse navbar-collapse" id="navbarNavDropdown">
            <ul class="navbar-nav ml-auto">
              <% if customer_signed_in? %>
                <p class="p-3 text-info">ようこそ、<%= current_customer.first_name %>さん</p>
                <li class="nav-item">
                  <%= link_to "マイページ", public_customer_path(current_customer.id), class: "fas fa-user nav-link text-teal m-3" %>
                </li>
                <li class="nav-item">
                  <%= link_to "商品一覧", public_items_path, class: "fas fa-gifts nav-link text-teal m-3" %>
                </li>
                <li class="nav-item">
                  <%= link_to "カート", public_cart_items_path, class: "fas fa-shopping-cart nav-link text-teal m-3" %>
                </li>
                <li class="nav-item">
                  <%= link_to "ログアウト", destroy_customer_session_path, method: :delete, class: "fas fa-sign-out-alt nav-link text-teal m-3" %>
                </li>
                <% elsif admin_signed_in? %>
                <li class="nav-item">
                  <%= link_to "商品一覧", admin_items_path, class: "nav-link text-white m-3 btn btn-sm btn-success" %>
                </li>
                <li class="nav-item">
                  <%= link_to "会員一覧", admin_customers_path, class: "nav-link text-white m-3 btn btn-sm btn-success " %>
                </li>
                <li class="nav-item">
                  <%= link_to "注文履歴一覧", admin_orders_path, class: "nav-link text-white m-3 btn btn-sm btn-success" %>
                </li>
                <li class="nav-item">
                  <%= link_to "ジャンル一覧", admin_genres_path, class: "nav-link text-white m-3 btn btn-sm btn-success" %>
                </li>
                <li class="nav-item">
                  <%= link_to "ログアウト", destroy_admin_session_path, method: :delete, class: "nav-link text-white m-3 btn btn-sm btn-success" %>
                </li>
                </div>
                <% else %>
                <li class="nav-item">
                  <%= link_to "About", homes_about_path, class: "fas fa-link nav-link text-teal m-3" %>
                </li>
                <li class="nav-item">
                  <%= link_to "商品一覧", public_items_path, class: "fas fa-gifts nav-link text-teal m-3" %>
                </li>
                <li class="nav-item">
                  <%= link_to "新規登録", new_customer_registration_path, class: "fas fa-user-plus nav-link text-teal m-3" %>
                </li>
                <li class="nav-item">
                  <%= link_to "ログイン", new_customer_session_path, class: "fas fa-sign-in-alt nav-link text-teal m-3" %>
                </li>
              <% end %>
            </ul>
          </div>
        </nav>
      </header>
      <main class="mt-3 mb-3">
      <%= yield %>
      </main>
    <footer>
      <div><p class="text-center mt-4">NaganoCake</p></div>
    </footer>
  </body>
</html>